### ISSUE TITLE
jupyterlab-wakatime extension not working

### ISSUE THREAD

**Issue by soullessness1611** [wakatime/jupyterlab-wakatime#1]
Hi

I installed jupyterlab-wakatime extension on jupyterlab but it not working. And not show status on Plugin Status at https://wakatime.com/plugins/status

![image](https://github.com/wakatime/jupyterlab-wakatime/assets/131554043/befbdd02-e815-4af6-8bc2-21bfbd7d1cbc)

![image](https://github.com/wakatime/jupyterlab-wakatime/assets/131554043/e0145315-0455-4aeb-bc91-6ac1d2dba912)

**Comment by AllanChain** [comment]
Thanks for your report! This plugin is in an early stage and the stability still needs improvement.

To debug this issue, I need more information. How are you running JupyterLab? Can you share your JupyterLab logs in your console?

**Comment by soullessness1611** [comment]
> Thanks for your report! This plugin is in an early stage and the stability still needs improvement.
> 
> To debug this issue, I need more information. How are you running JupyterLab? Can you share your JupyterLab logs in your console?

I run on terminal via command "jupyter lab".
![image](https://github.com/wakatime/jupyterlab-wakatime/assets/131554043/1e0f672a-7091-497c-a569-f249ef7a315c)

**Comment by AllanChain** [comment]
It needs extra works for Windows. Does version 0.1.4 work for you?

**Comment by soullessness1611** [comment]
> It needs extra works for Windows. Does version 0.1.4 work for you?

I tried upgrade to version 0.1.4, Right now it's worked for me.

Thank you very much for support.
![image](https://github.com/wakatime/jupyterlab-wakatime/assets/131554043/9016e019-d301-4af6-a7ee-43874444cc01)
